---

- name: Install dotfiles
  hosts: all

  tasks:
    - lineinfile:
        dest: ~/.zshrc
        create: yes
        line: "{{ item }}"
      loop:
        - "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh"
        - "bindkey -v"
        - "bindkey '^R' history-incremental-search-backward"
        - "function parse_git_branch() { git branch 2> /dev/null | sed -n -e 's/^\\* \\(.*\\)/[\\1]/p' }"
        - "COLOR_DEF=$'\\e[0m'"
        - "COLOR_USR=$'\\e[38;5;243m'"
        - "COLOR_DIR=$'\\e[38;5;197m'"
        - "COLOR_GIT=$'\\e[38;5;39m'"
        - "setopt PROMPT_SUBST"
        - "export PROMPT='${COLOR_USR}%n ${COLOR_DIR}%~ ${COLOR_GIT}$(parse_git_branch)${COLOR_DEF} $ '"
        - "export DOTNET_ROOT=$HOME/.dotnet"
        - "export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools"