---

- import_playbook: 'homebrew.yml'

- name: Install macOS Packages
  hosts: all

  tasks:
    - homebrew:
        name: "{{ item }}"
        state: latest
      loop:
        - asciinema
        - aws-iam-authenticator
        - docker-compose
        - fzf
        - ghc
        - helm
        - heroku
        - htop
        - k9s
        - kubectl
        - netcat
        - openjdk
        - postgresql
        - redis

    - homebrew_cask:
        name: "{{ item }}"
        state: latest
      loop:
        - docker
        - google-chrome
        - iterm2
        - lens
        - microsoft-remote-desktop
        - mysqlworkbench
        - postman
        - racket
        - wireshark
        - zoom